Entero a, b, c, num, i, acum
inicio
Escriba "Ingrese un numero mayor o igual a 10 y menor 100: "
Lea num
a<-0
b<-1
acum <- 0
	si (num >= 10) y (num <=100) entonces
		para i<-1 hasta num haga
			acum <- acum + a
			Escriba a
			c<-a+b
			a<-b
			b<-c
			llamar nueva_linea
		fin para
		escriba "Se mostraron ", num, " numeros"
		llamar nueva_linea
		escriba "La suma de todos los numeros es: ", acum
		sino 
			Escriba "Numero invalido"
	fin si
fin


