Entero x, num, contador, nPrimos
inicio
	num <- 0
	contador <- 0
	nPrimos <- 1
	mientras nPrimos <= 30 haga
		  num<- num + 1
		  x <- 1
		  contador <- 0
		  mientras x <= num haga
		  	si num mod x = 0 entonces
		  		contador <- contador + 1
		  	fin si
		  	x <- x + 1
		  fin mientras
		  si contador = 2 entonces
		  	escriba nPrimos,"->",num
		  	llamar nueva_linea
		  	nPrimos <- nPrimos + 1
		  fin si
	fin mientras
fin